# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scriberr < Formula
  desc "Audio transcription service using WhisperX with speaker diarization"
  homepage "https://github.com/rishikanthc/Scriberr"
  version "1.0.2"
  license "MIT"

  depends_on "uv"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.0.2/Scriberr_Darwin_x86_64.tar.gz"
      sha256 "478b337f049a251231371b8cd3d1f4fc54c48b17306a0024a203afe6be17d86e"

      def install
        bin.install "scriberr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.0.2/Scriberr_Darwin_arm64.tar.gz"
      sha256 "b0c1d318509bdc935314483e87aef3cb6ed2025668d3a65fd40692848e7035d2"

      def install
        bin.install "scriberr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.0.2/Scriberr_Linux_x86_64.tar.gz"
      sha256 "4571093c9debf7bb8c5b61fc57ceea4a8eaf0f30c7c144bc340def08c1c88ff5"
      def install
        bin.install "scriberr"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.0.2/Scriberr_Linux_arm64.tar.gz"
      sha256 "7035578664b8ab3277b168278dd77dd71aea35b37721585b62edf069f3ff7d09"
      def install
        bin.install "scriberr"
      end
    end
  end

  def caveats
    <<~EOS
      Scriberr requires Python 3.11+ for transcription features.
      Install with: brew install python@3.11

      To get started:
      1. Run: scriberr
      2. Open: http://localhost:8080

      The app will auto-configure itself on first run.
    EOS
  end

  test do
    system "#{bin}/scriberr", "--version"
  end
end
