# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scriberr < Formula
  desc "Audio transcription service using WhisperX with speaker diarization"
  homepage "https://github.com/rishikanthc/Scriberr"
  version "1.0.3"
  license "MIT"

  depends_on "uv"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.0.3/Scriberr_Darwin_x86_64.tar.gz"
      sha256 "5a7ffc8f69d1187e6a771bfde3a37d5b3cf1afacd970220ff49579723384fbb5"

      def install
        bin.install "scriberr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.0.3/Scriberr_Darwin_arm64.tar.gz"
      sha256 "46de47c0e0d2cb2fc8fd884a6e3a43706f3f083ca1f1be8d4aee8b6d00e2e080"

      def install
        bin.install "scriberr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.0.3/Scriberr_Linux_x86_64.tar.gz"
      sha256 "2854145cc9220494bff65867c665064dfd3d674c2ec8351cebcb17f45db214e5"
      def install
        bin.install "scriberr"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.0.3/Scriberr_Linux_arm64.tar.gz"
      sha256 "3e1c1fb10e64c687d958c7e6bad439b77f167c5ef579610da0fa533ed001db2b"
      def install
        bin.install "scriberr"
      end
    end
  end

  def caveats
    <<~EOS
      Scriberr requires Python 3.11+ for transcription features.
      Install with: brew install python@3.11

      To get started:
      1. Run: scriberr
      2. Open: http://localhost:8080

      The app will auto-configure itself on first run.
    EOS
  end

  test do
    system "#{bin}/scriberr", "--version"
  end
end
