# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scriberr < Formula
  desc "Audio transcription service using WhisperX with speaker diarization"
  homepage "https://github.com/rishikanthc/Scriberr"
  version "1.0.1"
  license "MIT"

  depends_on "uv"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.0.1/Scriberr_Darwin_x86_64.tar.gz"
      sha256 "0afd9d69a6ce8a65f9b5af61d0ae173d4261f53336d78ba66c1f95d29402d858"

      def install
        bin.install "scriberr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.0.1/Scriberr_Darwin_arm64.tar.gz"
      sha256 "2da722cceb0e1e52ff449167dcb7a911d954b9aa523885125ffeb332ec2223b7"

      def install
        bin.install "scriberr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.0.1/Scriberr_Linux_x86_64.tar.gz"
      sha256 "020beadbd5f98c61f86590d8796aa33437d6ac024b016c3a57f6159379cc9f8b"
      def install
        bin.install "scriberr"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.0.1/Scriberr_Linux_arm64.tar.gz"
      sha256 "1d0adcf2198dd356ba6fb50d62362a62abfe986541fe9986b4544e035ee7a6a2"
      def install
        bin.install "scriberr"
      end
    end
  end

  def caveats
    <<~EOS
      Scriberr requires Python 3.11+ for transcription features.
      Install with: brew install python@3.11

      To get started:
      1. Run: scriberr
      2. Open: http://localhost:8080

      The app will auto-configure itself on first run.
    EOS
  end

  test do
    system "#{bin}/scriberr", "--version"
  end
end
