# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scriberr < Formula
  desc "Audio transcription service using WhisperX with speaker diarization"
  homepage "https://github.com/rishikanthc/Scriberr"
  version "1.0.4"
  license "MIT"

  depends_on "uv"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.0.4/Scriberr_Darwin_x86_64.tar.gz"
      sha256 "82745a57d27acf6515e845942d13c38b5b2b1c08d22e8ad733d6e7212e6c40f4"

      def install
        bin.install "scriberr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.0.4/Scriberr_Darwin_arm64.tar.gz"
      sha256 "58e8e94f120a8e9c772f1ed7e978c3eec0dcc4592eebe49b5675b88d227b79da"

      def install
        bin.install "scriberr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.0.4/Scriberr_Linux_x86_64.tar.gz"
      sha256 "c4abc47bc33ae2d49abd42cf05c482e8380c6b9dabb35fde41072f1f73673804"
      def install
        bin.install "scriberr"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.0.4/Scriberr_Linux_arm64.tar.gz"
      sha256 "ab0a9aae45a7530eda18322119abcae64990c8497385a626f38d6d51d9efc6ac"
      def install
        bin.install "scriberr"
      end
    end
  end

  def caveats
    <<~EOS
      Scriberr requires Python 3.11+ for transcription features.
      Install with: brew install python@3.11

      To get started:
      1. Run: scriberr
      2. Open: http://localhost:8080

      The app will auto-configure itself on first run.
    EOS
  end

  test do
    system "#{bin}/scriberr", "--version"
  end
end
