# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scriberr < Formula
  desc "Audio transcription service using WhisperX with speaker diarization"
  homepage "https://github.com/rishikanthc/Scriberr"
  version "1.1.0"
  license "MIT"

  depends_on "uv"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.1.0/Scriberr_Darwin_x86_64.tar.gz"
      sha256 "1481d3e4b2e6ece92fc64cb54479a85b431b88a016b381b18bf81330a72d6fc6"

      def install
        bin.install "scriberr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.1.0/Scriberr_Darwin_arm64.tar.gz"
      sha256 "3ba30d67cc1947344a927762e3fd02717ce94bba22d7dba87fa1a7c1fcf46d46"

      def install
        bin.install "scriberr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.1.0/Scriberr_Linux_x86_64.tar.gz"
      sha256 "9812d4ccefdd18e6562ec3b60ea1c99a1849c3c1a4adc69c0717ac9d50970bb4"
      def install
        bin.install "scriberr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rishikanthc/Scriberr/releases/download/v1.1.0/Scriberr_Linux_arm64.tar.gz"
      sha256 "eb4648e780f4f60beafa769312c567961cbe6822b8ee8dc619474162159ef4d0"
      def install
        bin.install "scriberr"
      end
    end
  end

  def caveats
    <<~EOS
      Scriberr requires Python 3.11+ for transcription features.
      Install with: brew install python@3.11

      To get started:
      1. Run: scriberr
      2. Open: http://localhost:8080

      The app will auto-configure itself on first run.
    EOS
  end

  test do
    system "#{bin}/scriberr", "--version"
  end
end
